### ISSUE TITLE
java.lang.IllegalStateException: Not under a public suffix: unspecified.mail

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/yauaa#125]
```
java.lang.IllegalStateException: Not under a public suffix: unspecified.mail
at nl.basjes.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:588)
at nl.basjes.shaded.com.google.common.net.InternetDomainName.topPrivateDomain(InternetDomainName.java:408)
at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.extractCompanyFromHostName(UserAgentAnalyzerDirect.java:873)
at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.determineDeviceBrand(UserAgentAnalyzerDirect.java:906)
at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.hardCodedPostProcessing(UserAgentAnalyzerDirect.java:858)
at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.parse(UserAgentAnalyzerDirect.java:747)
at nl.basjes.parse.useragent.UserAgentAnalyzer.parse(UserAgentAnalyzer.java:78)
at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.parse(UserAgentAnalyzerDirect.java:694)
at nl.basjes.parse.useragent.annotate.UserAgentAnnotationAnalyzer.map(UserAgentAnnotationAnalyzer.java:119)
at com.bol.gdpr.din.useragent.CleanUseragent.clean(CleanUseragent.java:20)```

**Comment by nielsbasjes** [comment]
Fixed
