### ISSUE TITLE
Investigate Drill error during build.

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/yauaa#128]
```
Running nl.basjes.parse.useragent.drill.TestParseUserAgentFunctionField
12:19:44,840 [INFO ] DrillConfig                             :  254: Configuration and plugin file(s) identified in 77ms.
Base Configuration:
	- jar:file:/home/nbasjes/.m2/repository/org/apache/drill/drill-common/1.14.0/drill-common-1.14.0.jar!/drill-default.conf

Intermediate Configuration and Plugin files, in order of precedence:
	- jar:file:/home/nbasjes/.m2/repository/org/apache/drill/drill-common/1.14.0/drill-common-1.14.0-tests.jar!/drill-module.conf
	- jar:file:/home/nbasjes/.m2/repository/org/apache/drill/exec/drill-java-exec/1.14.0/drill-java-exec-1.14.0-tests.jar!/drill-module.conf
	- jar:file:/home/nbasjes/.m2/repository/org/apache/drill/drill-common/1.14.0/drill-common-1.14.0.jar!/drill-module.conf
	- jar:file:/home/nbasjes/.m2/repository/org/apache/drill/drill-logical/1.14.0/drill-logical-1.14.0.jar!/drill-module.conf
	- jar:file:/home/nbasjes/.m2/repository/org/apache/drill/memory/drill-memory-base/1.14.0/drill-memory-base-1.14.0.jar!/drill-module.conf
	- jar:file:/home/nbasjes/yauaa/udfs/drill/function/target/yauaa-drill-5.7.jar!/drill-module.conf
	- jar:file:/home/nbasjes/.m2/repository/org/apache/drill/exec/drill-java-exec/1.14.0/drill-java-exec-1.14.0.jar!/drill-module.conf

Overridden Properties:
	-drill.catastrophic_to_standard_out = true
	-drill.exec.sys.store.provider.local.path = /home/nbasjes/yauaa/udfs/drill/tests/./target/nl.basjes.parse.useragent.drill.TestParseUserAgentFunctionField/store
	-exec.errors.verbose = true
	-drill.exec.rpc.bit.server.threads = 2
	-drill.exec.scan.threadpool_size = 4
	-drill.exec.zk.refresh = 0
	-drill.exec.http.enabled = false
	-drill.exec.default_temporary_workspace = dfs.tmp
	-drill.exec.sys.store.provider.zk.blobroot = /tmp/drill/tests
	-drill.tmp-dir = /home/nbasjes/yauaa/udfs/drill/tests/./target/nl.basjes.parse.useragent.drill.TestParseUserAgentFunctionField/tmp
	-drill.exec.sys.store.provider.local.write = false
	-drill.classpath.scanning.cache.enabled = false


12:19:45,081 [WARN ] GuavaPatcher                            :   40: Unable to patch Guava classes.
javassist.CannotCompileException: by java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/google/common/base/Stopwatch"
	at javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:140)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95)
	at javassist.ClassPool.toClass(ClassPool.java:1143)
	at javassist.ClassPool.toClass(ClassPool.java:1106)
	at javassist.ClassPool.toClass(ClassPool.java:1064)
	at javassist.CtClass.toClass(CtClass.java:1275)
	at org.apache.drill.exec.util.GuavaPatcher.patchStopwatch(GuavaPatcher.java:66)
	at org.apache.drill.exec.util.GuavaPatcher.patch(GuavaPatcher.java:36)
	at org.apache.drill.exec.server.Drillbit.<clinit>(Drillbit.java:71)
	at org.apache.drill.test.ClusterFixture.startDrillbits(ClusterFixture.java:228)
	at org.apache.drill.test.ClusterFixture.<init>(ClusterFixture.java:146)
	at org.apache.drill.test.ClusterFixtureBuilder.build(ClusterFixtureBuilder.java:283)
	at org.apache.drill.test.ClusterTest.startCluster(ClusterTest.java:83)
	at nl.basjes.parse.useragent.drill.TestParseUserAgentFunctionField.setup(TestParseUserAgentFunctionField.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/google/common/base/Stopwatch"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:152)
	at javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134)
	... 33 more
```

**Comment by nielsbasjes** [comment]
Fixed
