### ISSUE TITLE
commons-logging dependency problem

### ISSUE THREAD

**Issue by erethir** [nielsbasjes/yauaa#165]
Hi again!

I'm having an issue when running the analyzer, from a clean test-project. I'm getting the following exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at nl.basjes.shaded.org.springframework.core.io.support.PathMatchingResourcePatternResolver.<clinit>(PathMatchingResourcePatternResolver.java:185)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.loadResources(UserAgentAnalyzerDirect.java:304)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.initialize(UserAgentAnalyzerDirect.java:244)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect$UserAgentAnalyzerDirectBuilder.build(UserAgentAnalyzerDirect.java:1500)
	at nl.basjes.parse.useragent.UserAgentAnalyzer$UserAgentAnalyzerBuilder.build(UserAgentAnalyzer.java:132)
	at com.testproject.Main.main(Main.java:8)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 7 more
```
Which occurrs due to that PathMatchingResourcePatternResolver is trying to load the LogFactory class during initialization, and there's no dependency on commons-logging. However I saw that this has been discussed in a previous issue #137 where it was suggested to use include spring-jcl. So when I try to include spring-jcl (or commons-logging for that matter) it works.

To reproduce, just use the test-project from #159, add kryo add run the Main class

**Comment by nielsbasjes** [comment]
I did some digging to find the best way to handle this.
In my opinion it depends on the project you are including Yauaa in so I simply created documentation about that.

https://yauaa.basjes.nl/README-Usage.html#troubles-with-logging-dependencies
