### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by farnetto** [nielsbasjes/yauaa#175]
**Describe the bug**
OutOfMemoryError on UserAgentAnalyzerDirect.parse

**Component where the bug happens**
[ ] Core analyzer
[ ] UDF : Flink/Beam/Nifi/...
[ ] Other

**To Reproduce**
Steps or code fragment to reproduce the behavior:
user-agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0

**Expected behavior**

**Screenshots**

**Additional context**
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$16(MatcherAction.java:379)
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$732/1114212287.calculateInformPath(Unknown Source)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412)
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$16(MatcherAction.java:379)
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$732/1114212287.calculateInformPath(Unknown Source)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412)
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$16(MatcherAction.java:379)
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$732/1114212287.calculateInformPath(Unknown Source)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412)
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$16(MatcherAction.java:379)
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$732/1114212287.calculateInformPath(Unknown Source)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412)
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$15(MatcherAction.java:372)
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$731/938838831.calculateInformPath(Unknown Source)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412)
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$4(MatcherAction.java:345)
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$720/543003478.calculateInformPath(Unknown Source)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412)
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$0(MatcherAction.java:331)
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$716/314326729.calculateInformPath(Unknown Source)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412)
	at nl.basjes.parse.useragent.analyze.MatcherAction.initialize(MatcherAction.java:166)
	at nl.basjes.parse.useragent.analyze.MatcherRequireAction.initialize(MatcherRequireAction.java:43)
	at nl.basjes.parse.useragent.analyze.Matcher.initialize(Matcher.java:225)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect$$Lambda$936/1747911910.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1258)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.initializeMatchers(UserAgentAnalyzerDirect.java:456)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.parse(UserAgentAnalyzerDirect.java:825)

**Comment by farnetto** [comment]
Here's my init code:

`@PostConstruct
    public void initYauaa() {
        uaa = UserAgentAnalyzer
                .newBuilder()
                .withField("DeviceClass")
                .withField("AgentNameVersionMajor")
                .build();
    }`

**Comment by farnetto** [comment]
Using v5.12

**Comment by farnetto** [comment]
Immediately previous log entry:

n.b.p.useragent.UserAgentAnalyzerDirect  : Initializing Analyzer data structures

**Comment by nielsbasjes** [comment]
How much memory does your application have?
How often do you create a new instance?
Please provide an "as small as possible" example project so I can reproduce this?

**Comment by nielsbasjes** [comment]
From your error I think the problem is really a garbage collection problem. Are you trying to create a new instance for each request? If so then that would explain this error. Create a single instance and reuse that many times!

**Comment by farnetto** [comment]
Sorry, can't reproduce locally. Occurs inside google app engine. Here's another stack trace:

com.google.apphosting.api.DeadlineExceededException: This request (0000016da7ad3195) started at 2019/10/07 19:23:28.533 UTC and was still executing at 2019/10/07 19:24:32.497 UTC.
	at java.util.Arrays.copyOf(Arrays.java:3332) ~[na:1.8.0_171-google-v7]
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124) ~[na:1.8.0_171-google-v7]
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448) ~[na:1.8.0_171-google-v7]
	at java.lang.StringBuilder.append(StringBuilder.java:136) ~[na:1.8.0_171-google-v7]
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$16(MatcherAction.java:379) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$732/747699976.calculateInformPath(Unknown Source) ~[na:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$16(MatcherAction.java:379) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$732/747699976.calculateInformPath(Unknown Source) ~[na:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$16(MatcherAction.java:379) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$732/747699976.calculateInformPath(Unknown Source) ~[na:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$16(MatcherAction.java:379) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$732/747699976.calculateInformPath(Unknown Source) ~[na:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$15(MatcherAction.java:372) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$731/55478544.calculateInformPath(Unknown Source) ~[na:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$4(MatcherAction.java:345) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$720/348985128.calculateInformPath(Unknown Source) ~[na:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.lambda$static$0(MatcherAction.java:331) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction$$Lambda$716/950597327.calculateInformPath(Unknown Source) ~[na:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:412) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherAction.initialize(MatcherAction.java:166) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.MatcherRequireAction.initialize(MatcherRequireAction.java:43) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.analyze.Matcher.initialize(Matcher.java:225) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect$$Lambda$977/1186250899.accept(Unknown Source) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1258) ~[na:1.8.0_171-google-v7]
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.initializeMatchers(UserAgentAnalyzerDirect.java:456) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.parse(UserAgentAnalyzerDirect.java:825) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.UserAgentAnalyzer.parse(UserAgentAnalyzer.java:87) ~[yauaa-5.12.jar:na]
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.parse(UserAgentAnalyzerDirect.java:792) ~[yauaa-5.12.jar:na]

**Comment by farnetto** [comment]
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by farnetto** [comment]
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333) [runtime-impl-third-party.jar:na]
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213) [runtime-impl.jar:na]

**Comment by farnetto** [comment]
I have a single instance in my @Controller. Maybe has something to do with gae's deserialization.

**Comment by nielsbasjes** [comment]
The demo web thingy ( https://try.yauaa.basjes.nl ) I have created runs perfectly on a free Google app engine instance.

So far my best guess is that you either give this system not enough memory and/or you are creating a new instance for each request.

As I requested before: please provide me an example project so I can reproduce the problem (on appengine is that is needed).

**Comment by nielsbasjes** [comment]
The DeadlineExceededException may be caused by the fact that on appengine (which is really really slow) the initialisation takes > 30 seconds.
So run the initialisation at startup before accepting any requests.

**Comment by farnetto** [comment]
Ok, thanks for the info. Sorry I can't provide any more details.
