### ISSUE TITLE
NPE on MatcherAction.reset()

### ISSUE THREAD

**Issue by Flo354** [nielsbasjes/yauaa#82]
Hi,

With version 4.3, I receive a NPE when trying to parse a user agent.

> java.lang.NullPointerException: null
	at nl.basjes.parse.useragent.analyze.MatcherAction.reset(MatcherAction.java:459)
	at nl.basjes.parse.useragent.analyze.MatcherRequireAction.reset(MatcherRequireAction.java:65)
	at nl.basjes.parse.useragent.analyze.Matcher.reset(Matcher.java:410)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.parse(UserAgentAnalyzerDirect.java:757)
	at nl.basjes.parse.useragent.UserAgentAnalyzer.parse(UserAgentAnalyzer.java:73)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.parse(UserAgentAnalyzerDirect.java:722)
	at modules.uaparser.UAParser.parse(UAParser.java:50)
	at ***.***(***.java:***)
	at ***.***(***.java:***)

My user agents:

> Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

My code:

```java
UserAgentAnalyzer uaa = UserAgentAnalyzer
                    .newBuilder()
                    .hideMatcherLoadStats()
                    .withField("OperatingSystemClass")
                    .withField("OperatingSystemName")
                    .withField("AgentName")
                    .withField("AgentVersionMajor")
                    .build();

uaa.parse(userAgent);
```

**Comment by nielsbasjes** [comment]
To reproduce this I added this unit test, which passed cleanly.
Do you have more information because so far I'm not able to reproduce this problem.

```
@Test
public void testNormalUsage() {
    UserAgentAnalyzer uaa = UserAgentAnalyzer
        .newBuilder()
        .hideMatcherLoadStats()
        .withField("OperatingSystemClass")
        .withField("OperatingSystemName")
        .withField("AgentName")
        .withField("AgentVersionMajor")
        .build();

    String[] userAgents = {
        "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0",
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
    };

    for (String userAgent : userAgents) {
        UserAgent parsedAgent = uaa.parse(userAgent);
    }
}
```

**Comment by Flo354** [comment]
Ok, found the root problem.

```java
@Singleton
public class UAParser implements UAParserInterface {

    private final SecureRandom secureRandom = new SecureRandom();

    private final List<UserAgentAnalyzer> uaaList;

    public UAParser() {
        Logger.debug("Initializing user agents analyzer");
        uaaList = new ArrayList<>();

        new Thread(() -> {
            UserAgentAnalyzer.UserAgentAnalyzerBuilder uaab = UserAgentAnalyzer
                    .newBuilder()
                    .hideMatcherLoadStats()
                    .withField("OperatingSystemClass")
                    .withField("OperatingSystemName")
                    .withField("AgentName")
                    .withField("AgentVersionMajor");

            for (int i = 0; i < 2; ++i) {
                long startTime = System.currentTimeMillis();
                uaaList.add(uaab.build());
                long stopTime = System.currentTimeMillis();
                Logger.debug("User agent analyzer " + i + " initialized in " + (stopTime - startTime) + "ms");
            }
        }).start();
    }

    @Override
    public UserAgent parse(String userAgent) {
        while (uaaList.isEmpty()) {
            try {
                Thread.sleep(100);
            } catch (InterruptedException ignore) {}
        }

        return uaaList.get(secureRandom.nextInt(uaaList.size())).parse(userAgent);
    }
}
```

```java
public class DefaultController extends Controller {

    private final UAParserInterface uaParser;

    @Inject
    public DefaultController(UAParserInterface uaParser) {
        this.uaParser = uaParser;
    }
    
    public Result index() {
        Logger.debug("Parsing user agent");
        String ua = uaParser.parse(request().header("User-Agent").orElse("")).getUserAgentString();
        Logger.debug("Parsed user agent");
        return ok(ua);
    }
}
```

When I am using the same variable `uaab` in the constructor of the class `UAParser` for two differents analyzer, there is the null pointer exception, as soon as the two `UserAgentAnalyzer` are instantiated...

> [info] play.api.Play - Application started (Dev)
[debug] application - Parsing user agent
[debug] application - User agent analyzer 0 initialized in 1136ms
[debug] application - Parsed user agent
[debug] application - User agent analyzer 1 initialized in 298ms
[debug] application - Parsing user agent
[error] application - ! @780776eng - Internal server error, for (GET) [/] ->
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:343)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:341)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException: null
	at nl.basjes.parse.useragent.analyze.MatcherAction.reset(MatcherAction.java:459)
	at nl.basjes.parse.useragent.analyze.MatcherRequireAction.reset(MatcherRequireAction.java:65)
	at nl.basjes.parse.useragent.analyze.Matcher.reset(Matcher.java:410)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.parse(UserAgentAnalyzerDirect.java:757)
	at nl.basjes.parse.useragent.UserAgentAnalyzer.parse(UserAgentAnalyzer.java:73)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.parse(UserAgentAnalyzerDirect.java:722)
	at modules.uaparser.UAParser.parse(UAParser.java:52)
	at controllers.DefaultController.index(DefaultController.java:25)
	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$2(Routes.scala:70)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:134)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:133)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:108)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:88)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
	at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:138)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
	at scala.concurrent.impl.Promise.transform(Promise.scala:29)
	at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
	at scala.concurrent.Future.map(Future.scala:288)
	at scala.concurrent.Future.map$(Future.scala:288)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
	at scala.concurrent.Future$.apply(Future.scala:654)
	at play.core.j.JavaAction.apply(JavaAction.scala:138)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
	at scala.util.Try$.apply(Try.scala:209)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
	at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:337)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
	... 12 common frames omitted

But if I do it like that:

```java
        new Thread(() -> {
            for (int i = 0; i < 2; ++i) {
                long startTime = System.currentTimeMillis();

                UserAgentAnalyzer.UserAgentAnalyzerBuilder uaab = UserAgentAnalyzer
                        .newBuilder()
                        .hideMatcherLoadStats()
                        .withField("OperatingSystemClass")
                        .withField("OperatingSystemName")
                        .withField("AgentName")
                        .withField("AgentVersionMajor");

                uaaList.add(uaab.build());
                long stopTime = System.currentTimeMillis();
                Logger.debug("User agent analyzer " + i + " initialized in " + (stopTime - startTime) + "ms");
            }
        }).start();
```

No NPE anymore

**Comment by nielsbasjes** [comment]
Ok, So if I understand correctly doing builder.Build()     multiple times using  the two results causes problems. That seems logical and a point where I can put some safeguards.

I'll investigate further. Thanks.

**Comment by Flo354** [comment]
Yes, that's right.

But weirdly, I never have had the problem since I use yauaa with the exact
same code.

Le dim. 13 mai 2018 à 9:42 AM, Niels Basjes <notifications@github.com> a
écrit :

**Comment by nielsbasjes** [comment]
I dug into the code and I in the older version you would end up with a single partially corrupted instance.
In 4.3 I rewrote much of the initialization code which made the NPE surface.
I'm working on a fix to make the builder fail if you call any method of the builder after calling build (i.e. build/setter).

**Comment by nielsbasjes** [comment]
Please try what I have changed.

**Comment by Flo354** [comment]
It seems to work!

**Comment by nielsbasjes** [comment]
Thanks for helping out.
