### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Tsyklop** [nielsbasjes/yauaa#88]
I run my web application on Tomcat8. OS Ubuntu 16.04. 4GB RAM

I create `UserAgentAnalyzer` in JavaEE filter in init method:

```
@WebFilter(filterName = "Widget", urlPatterns = "/f/*")
public class Widget implements Filter {

    private static UserAgentAnalyzer userAgentAnalyzer;

    public void init(FilterConfig config) throws ServletException {

        userAgentAnalyzer = UserAgentAnalyzer
                .newBuilder().withFields("DeviceClass", "DeviceName", "OperatingSystemName")
                .dropTests().hideMatcherLoadStats().keepTests().withCache(25000).build();

    }
    ...
}
```

On my PC all right, but on Ubuntu i get error:
```
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1010)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:402)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1542)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:286)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:394)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:339)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:933)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:453)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:420)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:435)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:411)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:435)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:411)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:435)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:411)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:435)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:411)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:435)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:411)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:403)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:367)
	at nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:350)
	at nl.basjes.parse.useragent.analyze.MatcherAction.initialize(MatcherAction.java:205)
	at nl.basjes.parse.useragent.analyze.Matcher.initialize(Matcher.java:241)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect$$Lambda$9/1444635746.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.initializeMatchers(UserAgentAnalyzerDirect.java:369)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect.initialize(UserAgentAnalyzerDirect.java:194)
	at nl.basjes.parse.useragent.UserAgentAnalyzerDirect$UserAgentAnalyzerDirectBuilder.build(UserAgentAnalyzerDirect.java:1191)
	at nl.basjes.parse.useragent.UserAgentAnalyzer$UserAgentAnalyzerBuilder.build(UserAgentAnalyzer.java:132)
	at com.filter.Widget.init(Widget.java:45)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
```
I see memory used and: (it`s without your lib)
![default](https://user-images.githubusercontent.com/6783568/42025497-5da57ae6-7acd-11e8-8f82-c333fde44670.png)

why it's happened? why lib use all memory?

**Comment by nielsbasjes** [comment]
The library needs at least a few hundred MiB of memory ( check the readme! ). Also why do you set a cache of 25000? So the main question for me is : How much memory does your JVM have?

**Comment by Tsyklop** [comment]
where can I read more about the cache? What value should it be?

I do not know. I`m not change default configuration. I start my server from under IDEA. Perhaps the IDE itself sets the memory of the JVM. Where can I look?

**Comment by nielsbasjes** [comment]
In your case I would set the cache to 100
The memory impact is described here:
https://github.com/nielsbasjes/yauaa/blob/master/README.md#memory-usage

**Comment by Tsyklop** [comment]
about the memory, I understood. But that's about the cache, it's not entirely clear.
